version: "3.8"

services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - user_db

  user_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.dev
    command: gunicorn --bind 0.0.0.0:5005 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
      - ./CVPR2019:/dataset
    ports:
      - 5005:5005
    env_file:
      - ./.env2.dev

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  postgres_data:
