version: "3.4"

services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - user_db

  user_db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

  web:
    build:
        context: ./services/web
        dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5005:5005
    env_file:
      - ./.env2.dev

#  redis:
#    image: "redis:alpine"

  redis1:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
     - ./data/redis/6379/data:/data
   environment:
     - REDIS_PORT=6379
   ports:
     - '6379:6379'
     - '17001:17001'

  redis2:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
   - ./data/redis/6380/data:/data
   environment:
   - REDIS_PORT=6380
   ports:
     - '6380:6380'
     - '17002:17002'

  redis3:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
     - ./data/redis/6381/data:/data
   environment:
     - REDIS_PORT=6381
   ports:
     - '6381:6381'
     - '17003:17003'

  redis4:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
     - ./data/redis/6382/data:/data
   environment:
     - REDIS_PORT=6382
   ports:
     - '6382:6382'
     - '17004:17004'

  redis5:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
     - ./data/redis/6383/data:/data
   environment:
     - REDIS_PORT=6383
   ports:
     - '6383:6383'
     - '17005:17005'

  redis6:
   image: publicisworldwide/redis-cluster
   #network_mode: *default-netmode
   restart: always
   volumes:
     - ./data/redis/6384/data:/data
   environment:
     - REDIS_PORT=6384
   ports:
     - '6384:6384'
     - '17006:17006'


volumes:
  postgres_data:
